### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sbatschelet** [mrallen1/Net-Easypost#5]
@mrallen1 would it be possible to get a release for the latest PR from @melmothx  https://github.com/mrallen1/Net-Easypost/pull/4 ?  Thank you in advance for your time and consideration.

**Comment by mcmillhj** [comment]
@sbatschelet I will make a release this morning. Got caught up on a few other things and forgot to release after the last PR. Sorry for the delay!

**Comment by sbatschelet** [comment]
@mcmillhj not problem and thank you for quick reply!

**Comment by mcmillhj** [comment]
released: fb135763cf14597aacad1de33a675af54f408c72, should be available on CPAN soon.

**Comment by sbatschelet** [comment]
:+1:

**Comment by mcmillhj** [comment]
I was unaware that the module was being used. If that is the case, I will devote some time to making it feature complete.
